### ISSUE TITLE
Search function broken in Windows Universal Port

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#101]
Search no longer works in the latest WUP build

**Comment by astrojonathan** [comment]
That was fixed in the 1/9/15 check-in. Have you synced since then? The "Fix Catalog Initialization" was the issue. There was a race condition in the background initialization of catalogs. The creation and indexing were launch on separate background threads and the index was empty. Now they run sequentially in the same thread

**Comment by astrodavid** [comment]
I downloaded the latest version and built it 3 days ago when I posted this and it didn't work. I can try again...

**Comment by astrodavid** [comment]
search is still broken in WUP

**Comment by astrojonathan** [comment]
Fixed
