### ISSUE TITLE
Can't add Minor Planets into Layer Group

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-windows-client#49]
I would like to create a layer group of certain minor planets.  I can create the group fine.  And I right click on the group name in the layer manager and see "Add Minor Planet". When when I add a name (I know it is correct name since the same name works if it is added under Sun) I get the error: "The designation was now found or the MPC service was unavailable".

**Comment by astrojonathan** [comment]
Minor planets are a reference frame, you can't add reference frames to a layer group. 
In the current implementation Minor planets menu item appears anywhere in the tree with a right click, but can only add minor planets in their orbit around the sun.

You had already added the minor planet once, then tried adding it again to the layer group, and it failed since it was already there.

The issue should be changed to:
Minor Planet menu should only appear when right clicking on Sun.
Bette error message when adding a minor planet that was already exist.

Probably should close this bug and open two new issue as above.
